version: "3.9"
services:
  php:
    image: "php:8.1.15RC1-fpm-buster"
    working_dir: /app
    volumes:
      - ./:/app/index.php
  mysql:
    image: "mysql:8.0.32"
    environment:
      - MYSQL_ROOT_PASSWORD=password
